import Head from "next/head";
import { auth } from "../config/firebase";
import { useState, useEffect, SetStateAction } from "react";
import Quote from "./Quote";
import { useRouter } from "next/router";

export default function Home() {
  const [quotes, setQuotes] = useState();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      fetch("https://api.chucknorris.io/jokes/search?query=cats")
        .then((res) => res.json())
        .then((quotes) => {
          setQuotes(quotes.result);
          setIsLoading(false);
        });
    };
    fetchData() ;
  }, []);

  return (

    <div className="mt-5">
      <Head>
        <title>Chuck Quotes | Main</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="">
        <h1 className="">Quotes</h1>
        {isLoading ? (
          <h2>Loading... </h2>
        ) : (
          quotes?.map((q) => <Quote quote={q} key={q.id} />)
        )}
      </main>
    </div> 
    )
}